version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://user:user@book.9ap05.mongodb.net/health-data-system?retryWrites=true&w=majority&appName=Book
      - JWT_SECRET=your_jwt_secret_key_replace_in_production
    restart: unless-stopped